CREATE TABLE topico (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(200) NOT NULL,
  mensagem TEXT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(30) NOT NULL,
  autor VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL
);
